platform: 172.16.0.120

workspace:
  path: src/helm.sh/chartmuseum

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git-arm64:1.0
    pull: true
    dns: 223.5.5.5

pipeline:
  golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arm64:1.14.4-stretch
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    binary: chartmuseum
    main: cmd/chartmuseum

  docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-arm64:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine-arm64:3.9
    dockerfile: .beagle/dockerfile.arm
    repo: wod/awecloud-chartmuseum-arm64
    version: "v0.12.0"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-harbor-arm64:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: wod/awecloud-harbor-chartmuseum-arm64
    tag: "v1.8.6"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD     