ARG BASE

FROM $BASE
LABEL maintainer=mengkzhaoyun@gmail.com

RUN yum install -y  cifs-utils ca-certificates \
    && adduser -u 1000 chartmuseum 

COPY ./dist/chartmuseum /chartmuseum

VOLUME ["/chart_storage"]
EXPOSE 9999
USER 1000
ENTRYPOINT ["/chartmuseum"]
